sudo: required
language: node_js
services:
  - docker
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass --version "=3.4.8"'
  - 'gem install compass --version "=1.0.1"'
before_deploy:
  - if [ "$TRAVIS_BRANCH" == 'master' ]; then export UNLEASH_ENV='production'; fi
  - if [ "$TRAVIS_BRANCH" == 'master' ]; then export BOT_URL='http://bot.unleash.x-team.com'; fi
  - if [ "$TRAVIS_BRANCH" == 'master' ]; then export PROFILES_URL='https://txkaf3ohhf.execute-api.us-west-2.amazonaws.com/prod/profiles'; fi
  - grunt build
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh latest
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh staging
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh qa
    on:
      branch: qa
